使用prop-types定义属性,避免在0.49.0上崩溃
Durgaprasad-Budhwani/react-native-busy-indicator pull request #21
Opened 2017-10-28 15:16 UTC by chenmo230

2017-10-28 17:43 UTC, RealOrangeOne requested changes

2017-10-28 17:43 UTC, RealOrangeOne commented on package.json
> +    "prop-types": "^15.6.0"
This should probably be moved to `peerDependencies`, as it's required at runtime for the application

2017-11-26 21:12 UTC, joshhornby commented
Can this be merged?

2017-11-27 08:45 UTC, RealOrangeOne commented
@joshhornby Unfortunately not, until my requested changes are made anyway

2017-11-28 17:22 UTC, joshhornby commented
@RealOrangeOne I've made the changes on a new PR https://github.com/RealOrangeOne/react-native-busy-indicator/pull/22

2017-11-28 17:26 UTC, joshhornby commented
Actually it looks like this PR is doing it correctly:

https://github.com/facebook/prop-types#how-to-depend-on-this-package
https://github.com/facebook/prop-types/issues/44

So I believe you can close my PR and merge this one.

2017-12-04 21:45 UTC, joshhornby commented
I've tested and this is working correctly.

2017-12-05 11:39 UTC, RealOrangeOne commented
Ohh, I didn't know that, good to know! Just need the tests to pass now (I assume it's just the linter)

2017-12-05 11:55 UTC, joshhornby commented
@RealOrangeOne All tests are passing for the PR 👍

2017-12-05 13:48 UTC, RealOrangeOne commented
Oh, I read the wrong `X`, damn you GitHub!

2017-12-05 13:48 UTC, RealOrangeOne approved these changes

2017-12-05 13:49 UTC, merged

2017-12-06 21:31 UTC, joshhornby commented
Thanks for merging, can you cut a new release as well? @RealOrangeOne